name: 2023.$(Rev:rrr)

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'
variables:
  - name: containerRegistry
    value: 'Dev Acr Admin'
  - name: ImageTag
    value: $(Build.BuildNumber)
  - name: imageRepository
    value: la-middleware

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: Dockerfile
              containerRegistry: 'Dev Acr Admin'
              tags: |
                $(ImageTag)

          - task: PublishPipelineArtifact@1
            inputs:
              artifactName: 'manifests'
              path: 'devops/k8s'